#!/usr/bin/env bash
#301 redirection
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello world!" | sudo tee /var/www/html/index.html

place_holder="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$place_holder/" /etc/nginx/sites-enabled/default

sudo service nginx restart
