#!/usr/bin/env bash
#404 error redirection
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello world!" | sudo tee /var/www/html/index.html

server_name_placeholder="server_name _;"
redirect_me_placeholder="rewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/$server_name_placeholder/$server_name_placeholder\n\t$redirect_me_placeholder/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

listen_placeholder="listen 80 default_server;"
error_page_placeholder="error_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/$server_name_placeholder/$server_name_placeholder\n\t$listen_placeholder\n\t$error_page_placeholder/" /etc/nginx/sites-enabled/default

sudo service nginx restart
